// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9x49tX6T_O97OZ13IndV-JHACN4FvSCQ',
    appId: '1:31183033401:web:7b4242d149f92e483669e8',
    messagingSenderId: '31183033401',
    projectId: 'akademik-ppkh',
    authDomain: 'akademik-ppkh.firebaseapp.com',
    storageBucket: 'akademik-ppkh.firebasestorage.app',
    measurementId: 'G-28RBC613LN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqQHqYwuEeRyM8-xqR2IgO2PXNepR6du8',
    appId: '1:31183033401:android:5c065c4af5acfa313669e8',
    messagingSenderId: '31183033401',
    projectId: 'akademik-ppkh',
    storageBucket: 'akademik-ppkh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBitQay_i029C1zCit2w12_zlBzHMUOp-8',
    appId: '1:31183033401:ios:a455600c81a8f2623669e8',
    messagingSenderId: '31183033401',
    projectId: 'akademik-ppkh',
    storageBucket: 'akademik-ppkh.firebasestorage.app',
    iosBundleId: 'com.example.akademikPpkh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBitQay_i029C1zCit2w12_zlBzHMUOp-8',
    appId: '1:31183033401:ios:a455600c81a8f2623669e8',
    messagingSenderId: '31183033401',
    projectId: 'akademik-ppkh',
    storageBucket: 'akademik-ppkh.firebasestorage.app',
    iosBundleId: 'com.example.akademikPpkh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9x49tX6T_O97OZ13IndV-JHACN4FvSCQ',
    appId: '1:31183033401:web:495e25bcf2f83dfd3669e8',
    messagingSenderId: '31183033401',
    projectId: 'akademik-ppkh',
    authDomain: 'akademik-ppkh.firebaseapp.com',
    storageBucket: 'akademik-ppkh.firebasestorage.app',
    measurementId: 'G-YPWQ8HG2DH',
  );

}